# Generated by Django 5.2.7 on 2025-10-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_address_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
