# Generated by Django 5.2.7 on 2025-10-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='given_name',
            new_name='first_name',
        ),
    ]
