# Generated by Django 5.2.6 on 2025-10-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_given_name_customer_first_name'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO store_collection (title)
            VALUES ('collection1');
            """,
            """
            DELETE FROM store_collection
            WHERE title='collection1';
            """
        )
    ]
